### ISSUE TITLE
When adding filter 'reportType' or others to download_sales_and_trends_reports, invalid vendor number error.

### ISSUE THREAD

**Issue by rolflocher** [Ponytech/appstoreconnectapi#16]
Following your lead on another issue, I have been trying to get download_sales_and_trends_reports to work, but when I add any other filters to the example, I am told the vendor number is invalid. It doesn't mind the same vendor number when using the default filters.

**Comment by ppawlak** [comment]
Same as #15, I'll have a look as soon as possible.

**Comment by ppawlak** [comment]
@rolflocher I can't find which filter makes the vendor number invalid. Can you post an example?

**Comment by rolflocher** [comment]
I actually cannot reproduce this now, sorry about that. I should have saved my old code.

**Comment by ppawlak** [comment]
> I actually cannot reproduce this now, sorry about that. I should have saved my old code.

So I am closing this issue.
Feel free to re-open it if you find how to reproduce the error.
