### ISSUE TITLE
Financial FINANCE_DETAIL report

### ISSUE THREAD

**Issue by dror-g** [Ponytech/appstoreconnectapi#17]
Hi, I don't think this is an issue with this wrapper (which is great! thanks!), but maybe you can shed some light:

I'm trying to download the detailed financial report by using `download_finance_reports` and specifying `reportType: FINANCE_DETAIL` as per the [docs](https://developer.apple.com/documentation/appstoreconnectapi/download_finance_reports), 

But I'm getting `there were no sales for the date specified`. 
Using the default `reportType: FINANCIAL` works fine.

Am I missing a filter? or is the detailed report not available by the API? 
Thanks!

**Comment by ppawlak** [comment]
Hi @dror-g,

The doc you linked also says 
> This value is always FINANCIAL.
and 
> Possible values: FINANCIAL, FINANCE_DETAIL

which sounds contradictory.

I tried and got the same result as you.
Ddid you expect anything particular with the  _FINANCE_DETAIL_ type?

**Comment by dror-g** [comment]
Thanks for trying this @ppawlak ,
I was expecting a more detailed report.

If you browse to https://itunesconnect.apple.com/itc/payments_and_financial_reports/ ,
Click "Create Reports" at the top right, you can select type -
"All Countries and regions (Single File)" - which gives the same report as API "FINANCIAL" type,
"All Countries and regions (Detailed)" - the default option, which gives a very detailed report by day. I was hoping to get this one.. 

Also posted on Apple Developer Forum - https://forums.developer.apple.com/message/424720#424720

Thanks again for verifying!

**Comment by ppawlak** [comment]
I am closing this issue as it does not seem related to our usage of the API.
Please re-open if you find how to fetch the  FINANCE_DETAIL.
