### ISSUE TITLE
Error when use "invite_user"

### ISSUE THREAD

**Issue by AricWu** [Ponytech/appstoreconnectapi#23]
Hi when I use function "invite_user" ,I got error.
```python
if visible_apps is not None:
			post_data['data']['relationships'] = {'visibleApps': list(map(lambda a: {'id': a, 'type': 'apps'}, visible_apps))}
			post_data['data']['relationships'] = {'visibleApps': visible_apps_relationship}
```
`visible_apps_relationship` is not defined . Looks like you forget to the last line.
And just delete `post_data['data']['relationships'] = {'visibleApps': visible_apps_relationship}` also can not invite user correctly. 
I change the code to this and fixed this issue
``` python
if visible_apps is not None:
            visible_apps_relationship = list(
                map(lambda a: {'id': a, 'type': 'apps'}, visible_apps))
            visable_apps_data = {'visibleApps': {
                'data': visible_apps_relationship}}
            post_data['data']['relationships'] = visable_apps_data
```

**Comment by ppawlak** [comment]
Thanks for the report and the fix @AricWu !

I have [commited this fix](https://github.com/Ponytech/appstoreconnectapi/commit/4d2716214105744e5016d1ff27be8cdb04aafd5b) and published a new version 0.8.3
