### ISSUE TITLE
Request for getting user.visibleApps

### ISSUE THREAD

**Issue by yangcaixing** [Ponytech/appstoreconnectapi#31]
Hi Patrice, 
     As request, I open this issue for getting user's visible apps, thanks for your great help.

**Comment by ppawlak** [comment]
I have just pushed a commit (https://github.com/Ponytech/appstoreconnectapi/commit/0c621cc82666ad28b785c36a957707279a3fc159) on master that should let you do this:

```python
users = api.list_users(filters={'username': 'john@example.org'})
user = users[0]  # note that you can now access an object using indexing
for app in user.visibleApps():
    print(app.name)
```

@yangcaixing can you confirm this works for you?

**Comment by yangcaixing** [comment]
Hi Patrice,  it works, thanks.

**Comment by ppawlak** [comment]
>  it works, thanks.

Great!
