### ISSUE TITLE
How can i get the analytics metrics data?

### ISSUE THREAD

**Issue by DrPolloLoco** [Ponytech/appstoreconnectapi#34]
I don't see the function in the library to get perfPowerMetrics

**Comment by ppawlak** [comment]
Thanks for reporting it.

[perfPowerMetrics ](https://developer.apple.com/documentation/appstoreconnectapi/perfpowermetric) is available in App Store Connect API 1.2+ which is not supported yet.

There is a branch https://github.com/Ponytech/appstoreconnectapi/tree/api-1.2 where I started the work. I'll try to add this as soon as possible.

**Comment by DrPolloLoco** [comment]
do you know if somehow i can connect me with app analytics? I need installs and uninstalls data.

**Comment by ppawlak** [comment]
> I need installs 

For installs your can download sales reports, documented here : https://developer.apple.com/documentation/appstoreconnectapi/download_sales_and_trends_reports
This is supported by the current version of this library, see the README for an example.

> and uninstalls data.

I don't think this is possible at the moment. 
The list of things available through the App Store API is listed here: https://developer.apple.com/documentation/appstoreconnectapi
I see nothing about uninstalls

**Comment by ppawlak** [comment]
I started playing around with the https://api.appstoreconnect.apple.com/v1/apps/{id}/perfPowerMetrics endpoint and here is an example of the JSON returned:

[perfPowerMetrics.txt](https://github.com/Ponytech/appstoreconnectapi/files/5954411/perfPowerMetrics.txt)

@DrPolloLoco I am not sure I can do anything with those data but returned them raw. Will this work for your use case? Do you know how to interpret those values?

**Comment by DrPolloLoco** [comment]
I had been confused, i thought that with powerMetrics could have the installs and uninstalls metrics. Ty for your help
