### ISSUE TITLE
Avoid pinned dependencies

### ISSUE THREAD

**Issue by josepanguera** [Ponytech/appstoreconnectapi#35]
On 8de43ea the dependencies were pinned in `setup.py`. The problem with that is that now is now longer possible to install this library and, for instance, the latest release of `requests` alongside.

Since I believe this project has the vocation of being a library and not a standalone project I suggest to instead of pinning the dependencies just force minimum versions*.

I'd be very happy to do a PR if you agree with it.

\*I know that `jwt 2.*` is problematic. For that particular dependency we could just set a minimum and a maximum version.

**Comment by ppawlak** [comment]
Hi @josepanguera, thanks for reporting this issue.

By "installing this library" do you mean system wide? I have never had this issue as I always use virtualenvs. What is your use case?
But anyway I don't see any reasons for setting only a minimum version dependency on requests. Please submit a PR

**Comment by josepanguera** [comment]
No, I meant inside a virtualenv but within a project that does uses other libraries. I explain myself badly :)

Anyway, I created the pr on #36.

**Comment by ppawlak** [comment]
> No, I meant inside a virtualenv but within a project that does uses other libraries.

OK make sense!
I'll merge the PR, I just let a comment about the cryptography package.

**Comment by ppawlak** [comment]
PR merged, thank you @josepanguera

**Comment by louisguitton** [comment]
hi @ppawlak could you cut a release on pypi with this change please 🙏

**Comment by ppawlak** [comment]
> 
> 
> hi @ppawlak could you cut a release on pypi with this change please 🙏

Wow, I didn't realized it was not released yet.
I'll do it shortly.

**Comment by ppawlak** [comment]
@louisguitton 
Version 0.9.1 including this fix is available : https://pypi.org/project/appstoreconnect/0.9.1/

Can you confirm this fixes dependencies on your project?

**Comment by louisguitton** [comment]
it does :) thank you @ppawlak for the quick response !
