### ISSUE TITLE
Un-hardcode Finance reportType

### ISSUE THREAD

**Issue by andrew-forbes-93** [Ponytech/appstoreconnectapi#45]
https://github.com/Ponytech/appstoreconnectapi/blob/1c4cac1cd1d84a7189e3a9e8d2c23d62bbc0a7fa/appstoreconnect/api.py#L639

Hi all, not sure if there's any activity here anymore. Thank you for this API! I'd like to use the download_finance_reports function to download FINANCE_DETAIL reports but the value is hardcoded as just FINANCE. 

Just curious if there's a reason this is the case? Maybe that wasn't an option when this package was created. Ideally it would just be another filter where I can set the value myself

**Comment by ppawlak** [comment]
Hi, 

Sorry for this very late reply, I should have replied earlier. This project this still active when I'm not busy elsewhere.

To answer your question, the _FINANCE_  value is not hard-coded but provided as a default value. You can pass an other reportType like this:

`api.download_finance_reports(filters={'vendorNumber': '123456', 'reportDate': '2021-10', 'reportType': 'FINANCE_DETAIL'}, save_to='finance.csv'` 

Please let me know if you have success with this: whatever date I try I always get this error:  _There were no sales for the date specified._

[Documentation](https://developer.apple.com/documentation/appstoreconnectapi/download_finance_reports) on Apple website is not very clear: 
![image](https://user-images.githubusercontent.com/1941270/174159956-e5db81e3-f440-4b25-a182-643d54a95d87.png)

There are 2 possible values but it is always one of them... 😕

**Comment by andrew-forbes-93** [comment]
Ha! Thank you, I'd forgotten about this. I think I eventually discovered
that I could do exactly what you posted.

Thanks again, this library has saved me a lot of time :)

**Comment by ppawlak** [comment]
> Thanks again, this library has saved me a lot of time :)

I'm really glad to hear that 😃
