### ISSUE TITLE
Accept pull requests?

### ISSUE THREAD

**Issue by EricG-Personal** [Ponytech/appstoreconnectapi#6]
I needed to get a list of devices associated with an account and your project provided a very nice base for doing that. I forked the project and added the support.

https://github.com/EricG-Personal/appstoreconnectapi/commit/12ae8f389e4ff787b9e8d8ff0be0fa9268362eba

 I think I got everything correct (or at least it worked for me). If you would like me to do a pull request, I can and you have one more API implemented.

**Comment by ppawlak** [comment]
Sure! Please do!

I just left a comment in your code.

**Comment by EricG-Personal** [comment]
Thanks for the suggestion. I will make the update to the code.

As for the content_type thing, based on what I’ve read, they all probably
should be using application/vnd.api+json ... at least according to
jsonapi.org

It is all just json.
